### ISSUE TITLE
How to set frame per second to accelerate the learning?

### ISSUE THREAD

**Issue by GoingMyWay** [mwydmuch/ViZDoom#209]
Hi, I don't know if the question has been asked. How can I set the frame per second? Are any APIs provided in ViZDoom?

I found `fps.py` in examples, however there is no code on this issue. Thank you!

**Comment by ebonyclock** [comment]
[set_ticrate
](https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md#setTicrate)

**Comment by mwydmuch** [comment]
For clarity: `set_ticrate` allows to speed up or slow down game in ASYNC modes (see ticrate.py example), because Doom's logic is tic depended, so there is no way to change framerate without affecting ingame time (only possibility is to skip frames and interpolate actions - skip argument in `make_action` is responsible for this).

**Comment by ebonyclock** [comment]
I assumed that it was obvious would make no sense in SYNC mode.

**Comment by mwydmuch** [comment]
We improved performance with Python's threading, so now the A3C-like methods should be much faster to learn.
