### ISSUE TITLE
Please can someone explain the following terms in very simple words for me.

### ISSUE THREAD

**Issue by adil25** [mwydmuch/ViZDoom#224]
Hello Everyone.  i am new to the area of VizDoom/Doom. Please can someone explain the following terms in very simple English or words with a little more detail for me. Thanks and forgive me if it looks a bit nonsense.
1) ViZDoom provides access to the renderer's depth buffer.
2) ViZDoom allows depth buffer access.
3) Off-screen Rendering and Frame skipping.
4) Reply Memory and Experience Reply

**Comment by ebonyclock** [comment]
1. For each state of the game you can access a screen buffer which is basically a picture of what the player would see playing doom. Additionally ViZDoom provides a depth buffer which is also a picture but instead of colors you get different intensity of pixels depending on how far given objects are from the player ([more about the idea of depth buffers](https://en.wikipedia.org/wiki/Z-buffering)
2. Well.. just a rephrasing of the first sentence?
3. For RL you often do not need to see the game, it's enough that you can copy the image as matrix and forward it to the algorithm. ViZDoom allows off-screen rendering which basically means that the image is rendered internally and not put on your screen anywhere so it's faster this way. 
Additionally you can omit rendering of some frames, for example you want your agent to see every fourth frame and you can achieve it in vizdoom without workarounds.
4. Replay (not reply) memory and Experience Replay are not part of ViZDoom, they are techniques used in popular RL algorithms like DQN. When making an action agent doesn't learn from it, it stores a transition in the replay memory (basically just some storage) - typically the action, reward, initial state, final state and if the state is terminal. Then an agent can perform the experience replay - it samples random transitions from the memory and trains on them in a mini-batch manner. This [example](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/learning_tensorflow.py) shows how to implement simple dqn with replay memory .

I hope that helped.

**Comment by adil25** [comment]
@ebonyclock ...Thanks a lot and it helped...........
