### ISSUE TITLE
Metrics in automap buffer

### ISSUE THREAD

**Issue by XinkeAE** [mwydmuch/ViZDoom#230]
Hi,

I have a question related to the metric/scale while using the automap buffer. I'm wondering how to convert the distance in the automap (in pixel) to the distance in vizdoom?

Thanks!

**Comment by mwydmuch** [comment]
Hello again @XinkeAE 
I can't easily answer your question, because default map's scale depends on the size of the current map and of course mapping pixels to distance depends on resolution.

But I've added 2 CCMDs that will allow you to setup your map:

```
game.send_game_command('am_grid 1')
game.send_game_command('am_scale 1')
``` 

First one will enable grid, size of the grid is 128 in map units, which maps to 3 meters.
Second allows to set absolute map zoom.

I hope this will help you.

**Comment by XinkeAE** [comment]
Thanks again @mwydmuch !

This is very helpful!
