### ISSUE TITLE
when the hp will be -999900?

### ISSUE THREAD

**Issue by jiahengqi** [mwydmuch/ViZDoom#262]
python3.5.2 ubuntu14
I find that somtimes the hp will be -999900 when I train my algrithom. Why?
game.get_game_variable(GameVariable.HEALTH)
and I never see it when I use it on Windows
our lab's server has no graphical interfaces, so I don't know what happens 
can I treat it as die?
my classmate say he find -999900 just after game.init() more than once, and that influenced our experiments.
I test the multiple_instances.py and it also happen.
I want to know how to solve it

Thanks

**Comment by Miffyli** [comment]
I am not 100% sure but I believe this to be sort of a placeholder-ish value when player is not really spawned/alive (some kind of initial value for the health variable, maybe). 

In any case, I patched around this just by clipping health with `max(game.get_game_variable(GameVariable.HEALTH),0)`, since practically negative health = zero health = dead. In some cases you could measure how much damage was taken from checking how far negative the health went, but you can patch around it too.

**Comment by jiahengqi** [comment]
Thanks
Actually, that's what I do
I just didn't have a good result  in the experiment, so I asked this question
