### ISSUE TITLE
KILLCOUNT in cig.wad is 0

### ISSUE THREAD

**Issue by Jeeeeeiel** [mwydmuch/ViZDoom#268]
i want to train my model in cig.wad, but i can't get the correct killcount, it's always zero.

**Comment by Miffyli** [comment]
When playing against other players (i.e. deathmatch mode), use `FRAGCOUNT` instead. `KILLCOUNT` is for measuring how many monsters (NPCs) have been killed.

Ultimately, if something does not work, you can adjust map's ACS scripts to give reward on certain events. You can see fine examples by opening example scenarios in SLADE 3.

**Comment by Jeeeeeiel** [comment]
but killing bot also doesn't change the KILLCOUNT

**Comment by Miffyli** [comment]
Bots are counted as "players" (they are "marines"), so use `FRAGCOUNT` instead.

**Comment by mwydmuch** [comment]
FRAGCOUNT and KILLCOUNT behave exactly as described by @Miffyli (thank you). This is the convention of Doom engine and we keep it here.

**Comment by Miffyli** [comment]
@jayhung97724 

Deathmatch scenario has built-in reward shaping for killing enemies (killing stronger enemies results in higher reward, ranging from 1.0 to 10.0). I.e. you only need to use the reward from e.g. `DoomGame.make_action(action,ticks)` functions to see if agent killed an enemy. If you want to use GameVariables, you should use `KILLCOUNT` here instead of `FRAGCOUNT` as this is not a player-vs-player game.

I am not 100% sure if the outdated GymDoom version has this reward shaping or valid GameVariables though. That version is rather outdated, and I suggest you use ViZDoom directly yourself (maybe somebody should write Gym env for this repo?).

**Comment by Miffyli** [comment]
There was some related discussions about this in an another issue but couldn't find it with it quick searching. Anywho: `KILLCOUNT` is slightly misleading because it counts total number of monsters (actors?) died, not specifically the ones player killed. Hence monsters accidentally killing each other count as "kills for you". If I remember correctly fixing this is difficult ( @mwydmuch ?).

`FRAGCOUNT` for multiplayer games (game arguments has `-deathmatch`) and modifying the reward signal for others should provide what you need.

**Comment by Neuroosi** [comment]
Hey, im trying to make my agent to play doom dm(deathmatch.wad), but for some reason bots wont die :D Any suggestions?

**Comment by Miffyli** [comment]
FRAGCOUNT measures the number of "frags" in a multiplayer game, not the number of monster kills (which are used in deathmatch.wad). Use `KILLCOUNT` instead.

(Sidenote, but the `KILLCOUNT` will include all kills done by anybody in the game, even when monsters kill each other)

**Comment by Neuroosi** [comment]
I removed the monsters and added bots(from bots.cfg) instead.

**Comment by Miffyli** [comment]
Hmm in that case it might still need to add `-deathmatch` flag to launch parameters for it to start tracking. [This code](https://github.com/Miffyli/gan-aimbots/blob/main/recording.py) running bots around correctly tracks FRAGCOUNT.
