### ISSUE TITLE
Creating custom objects 

### ISSUE THREAD

**Issue by satyaprky12** [mwydmuch/ViZDoom#291]
Hi,

Is it possible to create custom objects in this environment ? For instance 'redTorch' or 'yellowTorch'? and is their any doc for all the object types for this environment?

**Comment by michaelkrax** [comment]
You can use sendGameCommand (https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md#sendGameCommand) to send commands to the console of ZDoom which ViZDoom is based upon.

Via the console you can run a whole lot commands like spawning enemies or so or you can execute ACS scripts which is the build-in Doom map scripting language. The sky is the limit from there.

https://zdoom.org/wiki/CCMDs:Debug

Look for the puke command to run ACS scripts

A good starting point are the ZDoom Forums which include tons of tutorials for building custom maps and scripting them - or how to use the various tools for map making.

**Comment by ethanwaldie** [comment]
Hi there! So I am using slade and the DECORATE.txt file in order to create a custom thing for the environment. However, despite the object with showing up in SLADE with the correct name, the labels (and state.objects) returns an unknown name for this object. I was wondering how I could fix this. I tried editing the VizdoomGame.cpp so that I could manually map any unknown objects however the DoomEdNums are not attached to the share memory game objects. 

My file is something like this 

```
actor BlueKeyDoor : Candle 10001 {

}
```

Thanks in advance for the help!

**Comment by ethanwaldie** [comment]
I created a Hack to fix the naming by reading special arguments attached to each thing (specifically argument 1). The index of this arg corresponds to an index in a list of custom objects that can be passed in the config. 

https://github.com/ethanwaldie/ViZDoom
