### ISSUE TITLE
Altering scenarios

### ISSUE THREAD

**Issue by VladimirSlavic** [mwydmuch/ViZDoom#319]
Im trying to modify the defend_the_center scenario, to be specific i want to change the rewarding system a tad bit and add a negative reward for missed shots. My understanding is i have to access the acs and do the changes their. Also using doom builder 2, I'm curious if I should be using the builder for doom or doom 2? I thought this was doom 1 but i found this on the tutorial page for vizdoom: 
"freedoom2.wad is a free resource file with textures and other visual-related resources used by the game engine. The textures often differ from the original Doom's textures. Unfortunately, the original Doom2.wad file is proprietary, so we are not allowed to redistribute it - if you want to have nicer textures you need to acquire the file on your own (e.g., buy it on steam or gog) and place it in ViZDoom's installation path (e.g. /usr/local/lib/python2.7/dist-packages/vizdoom/doom2.wad) or set it with set_doom_game_path."

here it references the doom2.wad indicating that i should be using the builder for doom 2? Is there a way to just load the defend_the_center.wad and tweek it directly as i have no desire in doing any changes to the map or textures. In game configurations i have set the freedom2.wad in resources for doom, doom2 and zdoom even. When i then try to open defend_the_center.wad, i set game configuration first with doom then doom2 and finally zdoom and then it states that with the selected configuration, there should be some maps, however i see nothing for all three when i try them. Is there a link perhaps showing the editing of existing scenarios in vizdoom or something I'm missing that may be obvious to someone? Any help would be nice and thanks in advance as always.

**Comment by Miffyli** [comment]
You only need to tweak your scenario files when doing your own levels / ACS scripts. These will in some sense "override" what freedoom2.wad/doom.wad give (but use their textures/things/etcetc).

How do you want to modify the rewarding scheme? For giving negative reward per shot you can also track appropiate `GameVariable.AMMO` variables on each tick to see if it reduced (i.e. player fired a shot). Naturally this won't work with weapons with inf. ammo, like fists. 

Using the [SLADE](http://slade.mancubus.net/) editor you can modify ACS scripts of levels like this:
1. Open `defend_the_center.wad` in the SLADE (drag'n'drop or regular Open)
2. Open the "SCRIPTS" entry
3. Do your modifications to how `reward` variable is updated (this will be the reward you receive with when doing actions on Python side)
4. Save the ACS script entry **and compile it by right clicking on the entry -> Scripts -> Compile ACS**. Without compiling it won't work.
5. Save scenario.

To modify level layout you can open the `MAP##` entry in the editor. It will ask you some options about which game and resources to use. I seem to use "Doom (Ultimate), ZDoom" game and port. **Include the freedoom2.wad/doom.wad file with "Open Archive" button**, otherwise you will have missing textures and such.

**Comment by VladimirSlavic** [comment]
I can only thank you so much. You made this so simple. A note for anyone in the future who has never done anything with doom map builders or anything similar. Highly recommend slade and the zdoom wiki is a must to help you out with the functions, inventory items etc. 
Again, thank you so much for making life simple!
