### ISSUE TITLE
Rotation and translation of of camera motion

### ISSUE THREAD

**Issue by alexkreimer** [mwydmuch/ViZDoom#347]
Hi, is there a way to know/specify exact camera motion (rotation, translation) ?

**Comment by alexkreimer** [comment]
I just want to know how the camera moved relative to the scene when I issue a motion command.

**Comment by Miffyli** [comment]
Change in `GameVariable.PITCH/YAW` correspond to pitch/yaw of the camera, so you can track change in those GameVariables to get the rotation (i.e. difference of these values between two successive frames).

As for the location, tracking the change in `GameVariable.X/Y` is enough for those two coordinates. If you want exact position of camera, you need to  set the view bobbing to zero (see #323 ) and read the player's height via scenario ACS code into one of the `GameVariable.USER#` variables. Something like this:

```
global int 1:player_height;

script 2 ENTER
{
	while (1) {
        player_height = GetActorViewHeight(0);
        delay(1);
	}
}
```

This also includes changes by e.g. crouching, [according to the documents](https://zdoom.org/wiki/GetActorViewHeight), but I am unsure if this includes changes in height from head bobbing.

**Comment by mwydmuch** [comment]
Hello @alexkreimer,
it seams, the above function (thank you @Miffyli) does not take into account head bobbing, that's why I've added new variables that contains precise position and orientation of the camera.
In most cases camera's position will be equal to player's, however it is possible to program a scenario where camera is detached from first person perspective.

New variables:
* VIEW_HEIGHT - view high of the player
* CAMERA_POSITION_X - position of the camera
* CAMERA_POSITION_Y
* CAMERA_POSITION_Z - normally should be equal to POSITION_Z + VIEW_HEIGHT
* CAMERA_ANGLE - orientation of the camera in degrees
* CAMERA_PITCH
* CAMERA_ROLL
* CAMERA_FOV - field of view in degrees

**Comment by mwydmuch** [comment]
I think added variables provide requested information, closing.
