### ISSUE TITLE
Issue: Labels Report Invisible Objects (maybe behind walls?)

### ISSUE THREAD

**Issue by mhe500** [mwydmuch/ViZDoom#419]
Hi. In current ViZDoom (origin/master, compiled it myself) I'm seeing behavior where the labels list indicates an object that is not visible on the screen.

For example, the below is not visible (notice its screen width and height are zero). It's definitely not visible in the screen, but I know it's somewhere in the level. 

Is this known or expected behavior and if so is there a known work-around? For example, ignoring objects with width/height zero? Does that indicate in FOV but occluded?

Thanks!

5 = {Label} <vizdoom.vizdoom.Label object at 0x7f4aa414ae30>
 **height = {int} 0**
 object_angle = {float} 0.0
 object_id = {int} 240
 object_name = {str} 'DoomImp1'
 object_pitch = {float} 0.0
 object_position_x = {float} 347.0294189453125
 object_position_y = {float} 938.9705810546875
 object_position_z = {float} 16.0
 object_roll = {float} 0.0
 object_velocity_x = {float} 0.0
 object_velocity_y = {float} 0.0
 object_velocity_z = {float} 0.0
 value = {int} 36
 **width = {int} 0**
 x = {int} 221
 y = {int} 73

![image](https://user-images.githubusercontent.com/7040588/69366149-b23f2600-0c63-11ea-842f-d7a629b5f1c4.png)

**Comment by Miffyli** [comment]
Personally I have gotten around this issue by checking widths/heights, usually setting threshold to some low value (e.g. 3 pixels). A related issue with label buffers is that some walls are solid/opaque, but for some reason let labels through (e.g. there is a part like this in `map02` in `cig.wad`, if I remember correctly). Last time I checked these are more of issues with how ZDoom does rendering, rather than labeling.

**Comment by mhe500** [comment]
Thanks @Miffyli! That was my suspicion. I've worked around it per your suggestion.

Thanks again for all your answers.
mhe
