### ISSUE TITLE
Vizdoom website down again

### ISSUE THREAD

**Issue by LinxiFan** [mwydmuch/ViZDoom#438]
Same issue as #435 

Could you please consider hosting the website on [Github Pages](https://pages.github.com/) instead of the university website? University servers can be quite unreliable. Thanks!

**Comment by mwydmuch** [comment]
Hi @LinxiFan, thank you for reporting the problem, the webpage is up and running again! Our university server is quite stable, this and the previous issue was caused by a script left by our colleague. We removed it, so it won't happen again. 

Github Pages looks like a great solution for us, thanks for the idea, but unfortunately, as far I can see they are HTML and Jekyll only and our page is on PHP. Currently, we don't have time to change it.
