### ISSUE TITLE
"make" triggers a download

### ISSUE THREAD

**Issue by mboisson** [mwydmuch/ViZDoom#465]
### Questions, features suggestions and requests

Why does running `make` after configuring the build with `cmake` trigger the download of `freedoom2` ?
 
Either make `freedoom2` a proper dependency through CMake, or vendor it as part of your release, but please don't get `make` to download stuff.... 

This is incredibly bad practice...   a Makefile should be able to run offline.

**Comment by Miffyli** [comment]
I'll let @mwydmuch answer this in full.

**Comment by mwydmuch** [comment]
Hi @mboisson, thank you for pointing this out. Well, our knowledge about cmake/make good practices is probably very basic + ViZDoom was started as a student project a few years ago. Many bad design choices still remain from that period, because they generally work for us and others.

But actually, I'm going to update a lot of stuff related to dependencies/building/cmake soon and learn on the way how to do it more correctly. So @mboisson, it would be valuable for me to know what is the best way of doing it in your opinion? Do you think that moving downloading and extracting freedom.wad from make to cmake will be good enough? The freedoom is ~30mb, so I would prefer to have it outside of the repository.

**Comment by Flamefire** [comment]
To chime in here: The general point is: Each build should happen in the following, distinct stages:

- Download
- Configure
- Build
- Test
- Install

I.e. no download happens "automagically" during the configure or build step. This is so sources can be downloaded and verified(!) before building anything.   
It looks like although you can disable the Download via  `DOWNLOAD_FREEDOOM=OFF` it won't work due to this explicit dependency: https://github.com/mwydmuch/ViZDoom/blob/2cf7a5dc1a058a3e61a322e9af1b2cfba9cf80e0/src/lib_python/CMakeLists.txt#L71

I'm not sure for what this is required or how it is used but solutions are:
- use `find_package` to find an installed library and require users to install it upfront, maybe with a switch to (not) download it on configure time (e.g. if `USE_SYSTEM_FREEDOM` is set, require it to be installed already, else download)
- use git submodules and prepare release tarballs containing the populated submodules
- use CMakes new `FetchContent` to at least make CMake download the files during configure. That module provides ways to force an "offline" configure and to provide pre-populated source checkouts. I like that but others don't

If you got 20-something spare minutes check out this entertaining talk: https://www.youtube.com/watch?v=NSemlYagjIU

**Comment by mwydmuch** [comment]
Hi @Flamefire, thank you very much for your comment! I will check out the talk for sure and improve the building in the near feature.

**Comment by Flamefire** [comment]
Unrelated but some random ideas for improvement of CMake:

- check `project(.. VERSION)` instead of `ViZDoom*_VERSION`
- check `target_compile_features` instead of CMAKE_CXX_FLAGS for c++11
- generally try to use `target_*` instead of e.g. `include_directories`
- newer CMake has builtin support for `-fvisibility=hidden -fvisibility-inlines-hidden` and `-fPIC`
- I suggest to prefix all project-specific options with the project name, e.g. `BUILD_PYTHON3` -> `VIZDOOM_BUILD_FOR_PYTHON3`. This nicely groups them in e.g. ccmake/cmake-gui and avoids ambiguities
- Note: Don't be afraid to raise the required CMake version. CMake is very easy to install/update.

Besides this the CML looks quite good already :+1:

**Comment by mboisson** [comment]
> I'll let @mwydmuch answer this in full.
> 
> Edit: Gah sorry, clicked on wrong thing. By "proper dependency" you mean it should be already installed on the machine (e.g. as a package) or in some pre-defined directory? This sounds like bit of manual labour. Delegating the download of freedoom2 to Python/other library code could work, but needs to be implement in each supported language. The CMake file allows disabling the freedoom2 download, although is enabled by default.

Yes, I mean that the default should be that it must be already installed on the machine, as a package, in some findable (not pre-defined) location. As @Flamefire pointed out, disabling the download does not seem to work. 

Every single software package we install has to be reproducible. This means that we save source files and their checksums. Sources must not change over time. If the Make or Configure step downloads stuff, then it can't be guaranteed to be reproducible.

**Comment by mwydmuch** [comment]
Downloading of the freedom.wad was moved to the configuration step, and can be versioned by the variable in the last release. Thank you, @mboisson and @Flamefire, for all the suggestions. they were really helpful.
