### ISSUE TITLE
Windows Visual Studio 2015 error C2177: constant too big

### ISSUE THREAD

**Issue by bho008** [mwydmuch/ViZDoom#47]
Hello, I'm trying to build VizDoom using Windows 10 x64 and I'm getting tons of error of constant too big. I followed all the directions listed on zdoom, which worked perfectly fine. After adding the boost libraries and using the ViZDoom source, there's thousands of errors of constant too big.

**Comment by wjaskowski** [comment]
For Windows we recommend the binary version. Anyway, could you show the
error log?


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by bho008** [comment]
[vizdoomErrorLog.txt](https://github.com/Marqt/ViZDoom/files/241786/vizdoomErrorLog.txt)

Here's an error log. I'm having trouble running the python scripts on the precompiled binaries using Windows x64 also, but I'm still investigating that.

**Comment by wjaskowski** [comment]
Not a solution but two relevant stories:
1) https://community.trinitycore.org/topic/12039-i-have-this-problem
2)
http://quabr.com/34597039/compiling-with-boost-in-windows-10-results-in-errors-asio

**Comment by VSZM** [comment]
Is there any workaround for this one? I started out my project on ubuntu, but I couldn't find a working .wad editor.. Slade couldn't compile the scripts due to the lack of ACC. 

I figured I try it on windows, and there I could edit the maps to my liking. This I did in windows fine, but building VizDOOM has been a half a day nighmare and I'm stuck at this issue now..

**Comment by Marqt** [comment]
Yeah, building Windows version is a little pain due to all these paths. That's why we are providing compiled version. Why do you want to do it by yourself?

I'm using Win7, VS2013, CMake 2.8, Boost 1.59 to build ViZDoom for Windows and I haven't encountered any problem when compiling.

I found the information that downgrading CMake may help.
I would also try to select older Platform Toolset.
Also ViZDoom's CMake generate only x64 targets so maybe some 32bit/64bit version conflict?

Sorry if that wasn't much help, I don't have knowledge about all that Win/VS stuff.

**Comment by VSZM** [comment]
Compiled version? Can you point me to that one? I was following instructions in the Readme.md and that stated to build it our selves.

**Comment by Marqt** [comment]
There is information in README.md under Building -> Windows.

Link to 1.1.0pre version:
[https://github.com/Marqt/ViZDoom/releases/download/1.1.0pre-CIG2016-warm-up-fixed/ViZDoom-1.1.0pre-CIG2016-warm-up-Win-x86_64.zip](https://github.com/Marqt/ViZDoom/releases/download/1.1.0pre-CIG2016-warm-up-fixed/ViZDoom-1.1.0pre-CIG2016-warm-up-Win-x86_64.zip)

For other versions see "releases" tab.

**Comment by neroes** [comment]
seems to be a incompatibility issue with windows 10 and the windows 8.1 sdk

**Comment by neroes** [comment]
essentially it uses a variable to know what to do depending on os, no such value exist for windows 10 and it causes it to just read from memmory

**Comment by Marqt** [comment]
Good to know, thank you @neroes. Probably it will be fixed in next ZDoom released, then we will update engine version.
