### ISSUE TITLE
Unexpected behavior of "send_game_command" function

### ISSUE THREAD

**Issue by bahadirbasaran** [mwydmuch/ViZDoom#478]
Hello!
I have two questions related to the concerning function. I will be appreciated if you help me to understand.

1) If I use this function with a subsequent sleep, in order to see the behavior of the command, I need to wait until sleeping is being completed. As an example, even if  I call the function before "sleep", the menu is shown **after** 3 seconds:

    `game.send_game_command("menu_main")`
    `sleep(3)`

    Could this problem be caused due to the involvement of the ZDoom?

2) In a naive approach, I would expect to see two different screen buffers by running the code below. Even though the menu is shown on screen, the output indicates two completely identical screen buffers. What would cause this weird behavior?

    `state = game.get_state()`
    `print(state.screen_buffer)`
    `game.send_game_command("menu_main")`
    `state = game.get_state()`
    `print(state.screen_buffer)`

Thanks!

**Comment by Miffyli** [comment]
Hey! 

1) This is expected behaviour if you run ViZDoom in synchronized mode: the game waits for Python to `make_actions` before evolving the game state. In `GameMode.PLAYER_ASYNC` mode the game runs at a constant rate, regardless of Python functions. Do note that behaviour in main-menus is not something we have tested, so it might still result in undefined behaviour.

2) Same as above. You would have to call `make_actions`, possibly with large action-repetition to give main menu time to show up.

**Comment by bahadirbasaran** [comment]
Hey @Miffyli , thank you again for the super quick answer!

> Same as above. You would have to call advance_action, possibly with large number of tics to give main menu time to show up.

As you have suggested, if I change the code in the following way, I can obtain different buffers (but even if I give a small number of ticks like 1, I can see the menu):

    `game.advance_action(1)`
    `state = game.get_state()`
    `print(state.screen_buffer)`
    `game.send_game_command("menu_main")`
    `game.advance_action(1)`
    `state = game.get_state()`
    `print(state.screen_buffer)`

> This is expected behavior if you run ViZDoom in synchronized mode: the game waits for Python to advance_action before evolving the game state. In GameMode.PLAYER_ASYNC mode the game runs at a constant rate, regardless of Python functions.

I understood the reason why "get_state" and "advance_action" are tied to each other in the context of a synchronized game, but how is this fact also related to the issue in between "send_game_command" and "sleep"? What can I do to make it sleep after executing the command, not before (in sync. mode)?

**Comment by Miffyli** [comment]
> As you have suggested, if I change the code in the following way, I can obtain different buffers (but even if I give a small number of ticks like 1, I can see the menu):

This was the desired behaviour, no? On top of evolving the game state, `advance_action` updates the screen buffer on Python side (without calling it the `screen_buffer` does not change, even if the game has a different window).

> I understood the reason why "get_state" and "advance_action" are tied to each other in the context of a synchronized game, but how is this fact also related to the issue in between "send_game_command" and "sleep"? What can I do to make it sleep after executing the command, not before (in sync. mode)?

I am not sure if I quite understand the latter question. The issue here is the same that you need to evolve the game state with `advance_action` in order to see the effect of the command in game. Amount of sleeping does not affect the results. This works for me (opens up the menu and then sleeps for 3 seconds):

```python
game.send_game_command("menu_main")
game.advance_action(1)
sleep(3)
```

**Comment by mwydmuch** [comment]
@bahadirbasaran as @Miffyli said, `send_game_command` just adds a command to the engine's queue, the command will be executed in the next logic cycle, if you run it in SYNC mode, you need to call `advance_action` or `make_action` (that is calling `advance_action` internally) to give the engine a chance to process the command.

**Comment by bahadirbasaran** [comment]
> This was the desired behaviour, no?

Yes, I just meant that without a large number of tick, I can see the menu on the screen. So it is okay now. 

> as @Miffyli said: send_game_command just adds a command to the engine's queue, the command will be executed in the next logic cycle, if you run it in SYNC mode, you need to call advance_action or make_action (that calls advance_action internally) to give the engine a chance to process the command.
Generally, in SYNC mode engine is gathering commands to execute in the next logic cycle which is invoked by advance_action method. The state will never change if you don't call this method first.

I understood the point and corrected my code accordingly. Now it is working without any problem.

Thank you both for your clear and direct explanations!
