### ISSUE TITLE
Expand Gym Wrapper

### ISSUE THREAD

**Issue by bebeal** [mwydmuch/ViZDoom#505]
### Expand Gym Wrapper

I think it would be beneficial to expand the gym wrapper, specifically I think a good start would be the following improvements:

1. Allowing for all ViZDoom Screen Types
2. Allowing for delta buttons to be an option
3. Allowing for multiple buttons to be selected at once

I've been using a personal gym wrapper I made a while ago (https://github.com/bebeal/VizDoomGym) based on the same implementation that's already been implemented here, and allows for all screen types, and delta/multiple buttons. However, my personal gym wrapper has a lot of things fit to my specific use cases that I don't think should be included here, but figured I'd link it in case it can be of any use. I'm also willing to implement these two features myself if agreed upon.

**Comment by Miffyli** [comment]
Hey! Yup, I definitely agree with 2)  and 3). For 1), there is not really much reason to use other screen types, apart from GRAY8, but I am not sure if we want to encourage not using RGB images.

But yes, better support for varying action spaces would be better, as the single-button-at-time is [far from ideal](https://arxiv.org/abs/2004.00980) (done using [this env](https://github.com/Miffyli/rl-action-space-shaping/blob/master/envs/vizdoom_environment.py)). We could give the option to define how many buttons can be down at a time, which should be straight forward. 

I am not 100% what do for delta buttons: they could be new `Box` shape, but those add complexity to learning. We could force discretization (e.g. bin the range of valid buttons to multiple discrete choices), but that limits user.

**Comment by bebeal** [comment]
Fair enough on the screen types.

Hm why do you want to define how many buttons can be down at a time instead of allowing all of them to be down at once? Will the emulator break under certain circumstances? I guess I just assumed the user could easily limit that themselves if they were trying to put a constraint on an agent. 

I'm not so much a fan of forcing discretization as one of the specific use cases I created my wrapper for was using a gaussian agent to predict the delta value over the continuous range, and in general PPO/SAC algorithms are two very popular RL algorithms that allow for continuous distributions. But we could do this. 

What complexities were you worried about with using a `Box` shape?

**Comment by Miffyli** [comment]
> Hm why do you want to define how many buttons can be down at a time instead of allowing all of them to be down at once? Will the emulator break under certain circumstances? I guess I just assumed the user could easily limit that themselves if they were trying to put a constraint on an agent.

The main reasoning is that if you enable many buttons, creating all possible combinations of pressing them down (if you use `Discrete` space instead of `MultiDiscrete`) will create a huuuuge number of options. Limiting number of buttons pressed down is a simple way to prevent this. We could let user control this, too, with a `Wrapper`, but I think in its default (`Wrapper`-less) behaviour it should not be unusable.

> I'm not so much a fan of forcing discretization as one of the specific use cases I created my wrapper for was using a gaussian agent to predict the delta value over the continuous range, and in general PPO/SAC algorithms are two very popular RL algorithms that allow for continuous distributions. But we could do this.

Learning continuous control, especially in these game scenarios with mouse, [seems to be difficult](https://arxiv.org/abs/2004.00980), and often people discretize/bin it. It is also easier to simply support discrete choices instead of also having continuous actions along with continuous outputs. But yes, this too could be an option (or a wrapper) so that user gets the raw-est action spaces and then they can wrap it around whatever they like :).

I would be happy with a PR that adds these two:
 - Support for DELTA buttons by creating a `Dict` action space where each Delta button has `Box` action space, and button presses are in one big `Discrete` space
 - Support for multiple buttons pressed at once but with a default limit of, say, two buttons at a time at most.

**Comment by bebeal** [comment]
Got around to making a [PR](https://github.com/mwydmuch/ViZDoom/pull/508).

Lastly, I read the paper, it's definitely difficult but still possible ;-) https://github.com/bebeal/ContinuousDoom

**Comment by bebeal** [comment]
Added per https://github.com/mwydmuch/ViZDoom/pull/508
